import { fileURLToPath } from 'node:url';
import { migrate as migrateNodePg } from 'drizzle-orm/node-postgres/migrator';
import type { DatabaseConnection } from './client.js';

/** Directory holding the SQL migrations generated by drizzle-kit. */
export const MIGRATIONS_FOLDER = fileURLToPath(new URL('../drizzle', import.meta.url));

export async function migrate({ db }: DatabaseConnection): Promise<void> {
  await migrateNodePg(db, { migrationsFolder: MIGRATIONS_FOLDER });
}
